# Generated by Django 4.1.3 on 2024-06-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('celular', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('registroMercantil', models.CharField(default='0000-00', max_length=100, null=True)),
                ('tipoIdentificacion', models.IntegerField(choices=[(1, 'Registro civil'), (2, 'Tarjeta de identidad'), (3, 'Cédula de ciudadanía'), (4, 'Tarjeta de extranjería'), (5, 'Cédula de extranjería'), (6, 'NIT'), (7, 'Pasaporte'), (8, 'Documento de identificación extranjero'), (9, 'NIT de otro país'), (10, 'NUIP *')], default=3, null=True)),
                ('tipoOrganizacion', models.IntegerField(choices=[(1, 'Persona Jurídica'), (2, 'Persona Natural')], default=2, null=True)),
                ('regimen', models.IntegerField(choices=[(1, 'Responsable de iva'), (2, 'No responsable de iva')], default=2, null=True)),
                ('identificacion', models.CharField(max_length=100, null=True)),
                ('ciudad', models.IntegerField(choices=[(33, 'El Carmen de Viboral'), (1, 'Medellin')], default=33, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'entidades',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.IntegerField()),
                ('contabilizada', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('anulado', 'Anulado')], default='aprobado', max_length=8)),
                ('referencia', models.IntegerField(default=0)),
                ('formaPago', models.IntegerField(choices=[(1, 'Contado'), (2, 'Crédito')], default=1)),
                ('metodoPago', models.IntegerField(choices=[(10, 'Efectivo'), (20, 'Cheque'), (30, 'Transferecia Crédito'), (32, 'Transferencia Débito')], default=10)),
                ('estadoCuenta', models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('mora', 'Mora')], default='pagada', max_length=10)),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('fechaPago', models.DateTimeField(auto_now=True)),
                ('plazo', models.IntegerField(default=0)),
                ('importe', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('totalPagar', models.IntegerField(default=0)),
                ('sumImpuestos', models.IntegerField(default=0)),
                ('sumDescuentos', models.IntegerField(default=0, null=True)),
                ('pendiente', models.IntegerField(default=0)),
                ('totalPagado', models.IntegerField(default=0)),
                ('cambio', models.IntegerField(default=0)),
                ('fe_json', models.JSONField(blank=True, default=None, null=True)),
                ('resp_dian', models.JSONField(blank=True, default=None, null=True)),
                ('cufe', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion_electronica.entidad')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Filadescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(default=0)),
                ('cargo', models.BooleanField(default=False)),
                ('concepto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('cantidad_base', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Filaimpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(default=0)),
                ('cargo', models.BooleanField(default=False)),
                ('concepto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('cantidad_base', models.IntegerField(default=0)),
                ('porcentaje', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notadebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.IntegerField()),
                ('es_credito', models.BooleanField(default=False)),
                ('json', models.JSONField(blank=True, default=None, null=True)),
                ('resp_dian', models.JSONField(blank=True, default=None, null=True)),
                ('cude', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion_electronica.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Notacredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.IntegerField()),
                ('es_credito', models.BooleanField(default=False)),
                ('json', models.JSONField(blank=True, default=None, null=True)),
                ('resp_dian', models.JSONField(blank=True, default=None, null=True)),
                ('cude', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion_electronica.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default=None, null=True)),
                ('cedula', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('unidad_de_medida_cod', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('unidad_de_medida_name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('talla', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('valorUnitario', models.IntegerField(default=0)),
                ('descuento', models.IntegerField(default=0)),
                ('importe', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion_electronica.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Facturaimpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(default=0)),
                ('cargo', models.BooleanField(default=False)),
                ('concepto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('cantidad_base', models.IntegerField(default=0)),
                ('porcentaje', models.IntegerField(default=0)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion_electronica.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Facturadescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(default=0)),
                ('cargo', models.BooleanField(default=False)),
                ('concepto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('cantidad_base', models.IntegerField(default=0)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion_electronica.factura')),
            ],
        ),
    ]
