# Generated by Django 4.1.3 on 2024-06-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(max_length=10)),
                ('llave_tecnica', models.CharField(max_length=64)),
                ('desde', models.IntegerField(default=0)),
                ('hasta', models.IntegerField(default=0)),
                ('consecutivo', models.IntegerField(default=0)),
                ('fecha_desde', models.DateField(auto_now=True)),
                ('fecha_hasta', models.DateField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
