# Generated by Django 4.1.3 on 2024-06-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0002_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolucion',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
