# Generated by Django 4.1.3 on 2024-06-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0003_resolucion_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apidian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=64)),
            ],
        ),
    ]
