# Generated by Django 4.1.3 on 2024-06-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0004_apidian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apidian',
            old_name='token',
            new_name='token_api',
        ),
        migrations.AddField(
            model_name='apidian',
            name='token_dian',
            field=models.CharField(default='', max_length=64),
        ),
    ]
