# Generated by Django 4.1.3 on 2024-06-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0005_rename_token_apidian_token_api_apidian_token_dian'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='prefactura',
            field=models.IntegerField(default=0),
        ),
    ]
