# Generated by Django 4.1.3 on 2024-06-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0006_factura_prefactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='es_valida',
            field=models.BooleanField(default=False),
        ),
    ]
