# Generated by Django 4.1.3 on 2024-07-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0007_factura_es_valida'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidian',
            name='ambiente',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='apidian',
            name='certificate',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='apidian',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='apidian',
            name='pin',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='apidian',
            name='software_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='apidian',
            name='technical_key',
            field=models.CharField(default='', max_length=64),
        ),
    ]
