# Generated by Django 4.1.3 on 2024-07-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0008_apidian_ambiente_apidian_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resolucion',
            options={'verbose_name_plural': 'resoluciones'},
        ),
        migrations.AddField(
            model_name='apidian',
            name='nit',
            field=models.CharField(default='', max_length=16),
        ),
    ]
