kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: acueducto-pvc
  namespace: acueducto-madera
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
