# Generated by Django 4.1.3 on 2023-08-25 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nitcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codvie', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ciucte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('telcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('estrato', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('uso', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('dercon', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('alcant', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('aseo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('basico', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('complement', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('suntuario', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo1', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo3', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo4', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo5', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo6', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo7', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo8', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ficha', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('predio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('medidor', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('subsidio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('indsubsi', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('vereda', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ruta', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('lecact', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('feccon', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('lecant', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('indliq', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('enero', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conenero', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('febrero', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('confebrero', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('marzo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conmarzo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('abril', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conabril', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('mayo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conmayo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('junio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conjunio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('julio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conjulio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('agosto', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conagosto', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('septiembre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conseptiembre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('octubre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conoctubre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('noviembre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('connoviembre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('diciembre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('condiciembre', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codemp', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nit', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codage', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nomage', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('repleg', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ultcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fecpag', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('desde', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('hasta', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('dias', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'controles',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('formula', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codage', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('numdoc', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('numcom', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codcon', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fecmvt', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codcta', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('desmvt', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nitcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('debito', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('credito', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fecha', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-codcon'],
            },
        ),
        migrations.CreateModel(
            name='Subsidio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fecmvt', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nitcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('usuario', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cedula', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('estrato', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('debito', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('abonosub', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('saldosub', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('vrpagado', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Terminada', 'Terminada'), ('Bloqueada', 'Bloqueada')], max_length=16)),
                ('vereda', models.CharField(max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectura', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.consumo')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.ruta')),
            ],
        ),
    ]
