# Generated by Django 4.1.3 on 2022-12-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vereda', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('lecact', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('feccon', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('lecant', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('indliq', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('enero', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conenero', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('febrero', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('confebrero', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('marzo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conmarzo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('abril', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conabril', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('mayo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conmayo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('junio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conjunio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('julio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conjulio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('agosto', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conagosto', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('septiembre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conseptiembre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('octubre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('conoctubre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('noviembre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('connoviembre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('diciembre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('condiciembre', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codemp', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nit', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codage', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nomage', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('repleg', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ultcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fecpag', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('desde', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('hasta', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('dias', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codage', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('numdoc', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codcon', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fecmvt', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codcta', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('desmvt', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nitcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('debito', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('credito', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fecha', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subsidio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fecmvt', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nitcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('usuario', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cedula', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('estrato', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('debito', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('abonosub', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('saldosub', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('vrpagado', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
