# Generated by Django 4.1.3 on 2023-09-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='feccon',
            field=models.DateField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
