# Generated by Django 4.1.3 on 2022-12-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name_plural': 'controles'},
        ),
        migrations.AlterUniqueTogether(
            name='consumo',
            unique_together={('codcte', 'feccon')},
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together={('empresa', 'codemp', 'nit')},
        ),
        migrations.AlterUniqueTogether(
            name='movimiento',
            unique_together={('nitcte', 'desmvt', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='subsidio',
            unique_together={('factura', 'nitcte')},
        ),
    ]
