# Generated by Django 4.1.3 on 2023-08-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='lectura',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
