# Generated by Django 4.1.3 on 2024-04-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='lectura_anterior',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
