# Generated by Django 4.1.3 on 2023-08-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0002_alter_consumo_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo',
            name='cliente',
        ),
        migrations.AddField(
            model_name='consumo',
            name='codcte',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
