# Generated by Django 4.1.3 on 2023-09-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0002_consumo_ultimomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='ruta',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
