# Generated by Django 4.1.3 on 2023-08-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0002_alter_lectura_lectura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectura',
            options={'ordering': ['consumo__ruta']},
        ),
        migrations.AlterField(
            model_name='consumo',
            name='ruta',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
