# Generated by Django 4.1.3 on 2023-08-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0002_alter_dispositivo_codigo_alter_dispositivo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='vereda',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
