# Generated by Django 4.1.3 on 2024-06-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0003_consumo_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='facturado',
            field=models.BooleanField(default=False),
        ),
    ]
