# Generated by Django 4.1.3 on 2022-12-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0003_elemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='numcom',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
