# Generated by Django 4.1.3 on 2022-12-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0004_movimiento_numcom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elemento',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterUniqueTogether(
            name='movimiento',
            unique_together=set(),
        ),
    ]
