# Generated by Django 4.1.3 on 2024-06-27 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0003_resolucion_numero'),
        ('util', '0004_movimiento_facturado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='factura',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion_electronica.factura'),
        ),
    ]
