# Generated by Django 4.1.3 on 2022-12-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0005_alter_elemento_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subsidio',
            unique_together=set(),
        ),
    ]
