# Generated by Django 4.1.3 on 2024-07-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0005_movimiento_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='docref',
            field=models.IntegerField(default=0),
        ),
    ]
