# Generated by Django 4.1.3 on 2024-07-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0006_movimiento_docref'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='font',
            field=models.CharField(default='Times-Roman', max_length=32),
        ),
        migrations.AddField(
            model_name='elemento',
            name='size',
            field=models.IntegerField(default=12),
        ),
    ]
