# Generated by Django 4.1.3 on 2022-12-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0006_alter_consumo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['nitcte', 'codcon']},
        ),
    ]
