# Generated by Django 4.1.3 on 2023-08-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0008_alter_movimiento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-codcon']},
        ),
        migrations.AddField(
            model_name='consumo',
            name='ruta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumo',
            name='sector',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
