# Generated by Django 4.1.3 on 2023-08-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0009_alter_movimiento_options_consumo_ruta_consumo_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nitcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codvie', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ciucte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('telcte', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('estrato', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('uso', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('dercon', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('alcant', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('aseo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('basico', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('complement', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('suntuario', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo1', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo3', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo4', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo5', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo6', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo7', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('consumo8', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ficha', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('predio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('medidor', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('subsidio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('indsubsi', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
