# Generated by Django 4.1.3 on 2023-08-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0010_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo',
            name='codcte',
        ),
        migrations.AddField(
            model_name='consumo',
            name='cliente',
            field=models.ForeignKey(db_column='codcte', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='util.cliente'),
            preserve_default=False,
        ),
    ]
