# Generated by Django 4.1.3 on 2023-08-18 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0011_remove_consumo_codcte_consumo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vereda', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ruta', models.IntegerField(default=0)),
                ('lecturaAnterior', models.IntegerField(default=0)),
                ('lectura', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='codcte', on_delete=django.db.models.deletion.CASCADE, to='util.cliente')),
            ],
        ),
    ]
