# Generated by Django 4.1.3 on 2023-08-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0012_lectura'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
