# Generated by Django 4.1.3 on 2023-08-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0013_lectura_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='lectura',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='lecturaAnterior',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
