# Generated by Django 4.1.3 on 2023-08-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0014_alter_lectura_lectura_alter_lectura_lecturaanterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='codigo',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
