# Generated by Django 4.1.3 on 2023-08-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0015_alter_lectura_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='fecha_ruta',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
