kind: PersistentVolume
apiVersion: v1
metadata:
  name: acueducto-florida-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: acueducto-florida
    name: acueducto-pvc
  hostPath:
    path: "/mnt/acueducto_florida_data"